---
title: "KTH Theme for R"
kth_meta:
  twitter_card: "Summary info for the Twitter Card"
twitter_site: "\\@sitehandle"
twitter_creator: "\\@creatorhandle"
og_url: "https\\://example.com/open/graph/finalURLfor/this"
og_description: "A modest size description of the content"
og_image: "https\\://example.com/open/graph/imageURLfor/this"
output:
  ktheme::kth:
  toc: true
---

```{r include=FALSE}
knitr::opts_chunk$set(fig.retina=2)
```

```{r kth_setup, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE}
library(ktheme)
library(tidyverse)

update_geom_font_defaults(font_os)
```


This is an example plot and how a plot can look like using the `theme_kth()`:

## Figure

```{r, fig.show='hold', message=FALSE, echo=FALSE}

suppressPackageStartupMessages(library(bibliomatrix))

data <- abm_table4()

abm_graph_jcf(data) + theme_kth(grid = "XY")

```


```{r bib, include=FALSE}
# KEEP THIS AT THE END OF THE DOCUMENT TO GENERATE A LOCAL bib FILE FOR PKGS USED
knitr::write_bib(sub("^package:", "", grep("package", search(), value=TRUE)), file='skeleton.bib')
```

